name: CI Pipeline - Soma API

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      - name: Rodar Testes (Pytest)
        run: |
          pytest

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da Imagem Multi-stage
        run: |
          # Buildando a imagem com a tag latest
          docker build -t soma-api:latest -f Dockerfile .

      - name: Smoke Test (Healthcheck)
        run: |
          # 1. Sobe o container. Mapeamento 8001(host):8000(container)
          docker run -d -p 8001:8000 --name api-check soma-api:latest
          
          # 2. Aguarda o 'start-period' definido no Dockerfile (10s) + um pouco de margem
          echo "Aguardando o Healthcheck estabilizar..."
          sleep 15
          
          # 3. Debug: Mostra o status atual e logs se falhar
          docker ps
          
          # 4. Verifica se o status mudou para 'healthy'
          STATUS=$(docker inspect --format='{{json .State.Health.Status}}' api-check)
          echo "Status atual: $STATUS"
          
          if [[ "$STATUS" != "\"healthy\"" ]]; then
            echo "❌ Erro: Container não está saudável!"
            docker logs api-check
            exit 1
          fi
          echo "✅ Container saudável!"